### ISSUE TITLE
segfault when using php-skype

### ISSUE THREAD

**Issue by glensc** [gree/php-dbus#2]
trying to test  [php-skype](http://labs.gree.jp/Top/OpenSource/Skype-en.html) i get segmentation fault after

```
    $this->dbus_connection->registerObjectPath(self::dbus_path_notify, array($this, 'callback'));
```

dbus extension itself seems working using [tests/test-connection-fdo.php](https://github.com/glensc/php-dbus/blob/8fa07a7ecedca353c997745fd54703e7690ccd1c/tests/test-connection-fdo.php)

looks like null-pointer dereference

let me know of something more needed to nail this crash bug, for now attaching gdb backtrace:

```
$ gdb --args php skype_bot.php
GNU gdb (GDB) 7.4.50-0.20120120.2 (PLD Linux)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pld-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/php...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/php skype_bot.php
~/.bashrc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe7098700 (LWP 19758)]
[Thread 0x7fffe7098700 (LWP 19758) exited]
register /com/Skype/Client
invoke: NAME skype_bot

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff08a24a4 in _dbus_message_resource (obj=0x0) at /usr/src/debug/php-dbus-0.1.2/dbus.c:304
304 /usr/src/debug/php-dbus-0.1.2/dbus.c: No such file or directory.
(gdb) bt
#0  0x00007ffff08a24a4 in _dbus_message_resource (obj=0x0) at /usr/src/debug/php-dbus-0.1.2/dbus.c:304
#1  0x00007ffff08a2dfc in zif_dbus_connection_send_with_reply_and_block (ht=2, return_value=0xebfab8,     return_value_ptr=0x0, 
    this_ptr=0xeb7100, return_value_used=1) at /usr/src/debug/php-dbus-0.1.2/dbus.c:543
#2  0x00007ffff7af7129 in ?? () from /usr/lib64/libphp_common-5.3.15.so
#3  0x00007ffff7ab687b in execute () from /usr/lib64/libphp_common-5.3.15.so
#4  0x00007ffff7a91dae in zend_execute_scripts () from /usr/lib64/libphp_common-5.3.15.so
#5  0x00007ffff7a3fa46 in php_execute_script () from /usr/lib64/libphp_common-5.3.15.so
#6  0x000000000040423d in main ()
(gdb) 
```

**Comment by glensc** [comment]
for now i added NULL check:

```
--- php-dbus-0.1.2/dbus.c~    2012-08-18 21:26:28.064050848 +0300
+++ php-dbus-0.1.2/dbus.c    2012-08-18 21:26:29.844044834 +0300
@@ -298,6 +298,11 @@
 static DBusMessage* _dbus_message_resource(zval *obj TSRMLS_DC) {
     zval **tmp;
     int resource_type;
+    if (obj == NULL) {
+        fprintf(stderr, "WOOOT, obj is NULL\n");
+        return NULL;
+    }
+    printf("obj=%p\n", obj);
     dbus_objprop_get_p(obj, "message", tmp, 0);
     if (tmp == NULL) {
         return NULL;
```

this prevented segfault and threw an exception:

```
register /com/Skype/Client
obj=0xebf920
obj=0xebf920
obj=0xebf920
obj=0xebf920
obj=0xebf920
obj=0xebf920
invoke: NAME skype_bot
WOOOT, obj is NULL
PHP Fatal error:  Uncaught exception 'Exception' with message 'dbus_connection_send_with_reply_and_block() failed'     in /usr/share/php/Skype.php:109
Stack trace:
#0 /usr/share/php/Skype.php(86): Skype->invoke('NAME skype_bot', -1)
#1 /usr/share/php/Skype/Bot.php(86): Skype->connect()
#2 /usr/share/php/Skype/Bot.php(32): Skype_Bot->_startup()
#3 /home/glen/skype_bot.php(16): Skype_Bot->run()
#4 {main}
  thrown in /usr/share/php/Skype.php on line 109
[Inferior 1 (process 24336) exited with code 0377]
(gdb) 
```

**Comment by gamelaster** [comment]
Hey! I hate this problem, but here:

```
root@maidchan:~/php-skype-master# gdb --args php skype_bot.php
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/php skype_bot.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecfbd700 (LWP 9618)]
[Thread 0x7fffecfbd700 (LWP 9618) exited]
invoke: NAME ocastadmbot.maidchan
dbusmessage Object
(
    [message] => Resource id #20
)

Program received signal SIGSEGV, Segmentation fault.
_dbus_message_resource (obj=0x7fff00000000) at /root/php-dbus/dbus.c:308
308             dbus_objprop_get_p(obj, "message", tmp, 0);
(gdb) q
A debugging session is active.

        Inferior 1 [process 9614] will be killed.

Quit anyway? (y or n) y
```

You know how to fix that? :/
